### PR TITLE
docs: onboarding documentation

### PR DESCRIPTION
**Pull request by fmorency**
Onboarding documentation for
- Creating a MANY identity in Alberto/Gwen and with the CLI
- Creating a new token in Gwen and with the CLI
- Using the key-value store

PDF documentation is built on every PR.

Fixes liftedinit/management#15

### CODE REVIEW

**Comment by fmorency** [comment]
@tysloan You can get the latest PDF in [1]

[1]: https://output.circle-artifacts.com/output/job/f3603372-abb7-471c-869d-a2b10c9cf983/artifacts/0/artifacts/index_v1.0_ba362f51a3c13a2166dc3f09b6fb53ebadaeceaf.pdf

**Comment by tysloan** [comment]
Page 4: minor typo
This document provides instructions for each application.
Page 22:
DECIMALS Precision decimals. This is used to show how many tokens can be divided. 
Perhaps we should provide an example value for what is typical, like that Bitcoin is 8. 


DEST* MANY identities where the new tokens should be allocated
Can you allocate tokens it to multiple MANY identities?

**Comment by tysloan** [comment]
**Review notes:**
Page 4: minor typo
- "This document provides instructions for each application."

Page 22:
- DECIMALS Precision decimals. This is used to show how many tokens can be divided. 
> Perhaps we should provide an example value for what is typical, like that Bitcoin is 8. 

- DEST* MANY identities where the new tokens should be allocated
> Can you allocate tokens it to multiple MANY identities?

**Comment by fmorency** [comment]
> 

Thanks, @tysloan! I will fix those.

RE - DECIMALS
Bitcoin would be 9 in this context.

RE - DEST
The backend supports it, but the FE does not surface it. DEST is currently hardcoded to the Token Authority address in the FE.

**Comment by fmorency** [comment]
@tysloan you can find the fixes in [1]

[1]: https://output.circle-artifacts.com/output/job/f81fc044-54f6-44e4-9402-3d5d177ea152/artifacts/0/artifacts/index_v1.0_6ea0e13b2047d95ffc3414cff235de89525d1ee1.pdf

**Review by tysloan — APPROVED** [review]
Looks great!

**Pull request merged**
